java_binary(
    name = "inspector",
    main_class = "com.google.ajmichael.rules.RuleClassProviderInspector",
    srcs = ["RuleClassProviderInspector.java"],
    deps = [
        "//src/main/java/com/google/devtools/build/lib:bazel-rules",
        "//src/main/java/com/google/devtools/build/lib:build-base",
        "//src/main/java/com/google/devtools/build/lib:packages-internal",
    ],
)
